[tool.poetry]
name = "skynet"
version = "0.1.0"
description = ""
authors = ["Jitsi Team <team@jitsi.org>"]
readme = "README.md"

[tool.poetry.group.dev.dependencies]

[tool.poetry.dependencies]
fastapi = "0.101.1"
fastapi-versionizer = "0.1.6"
langchain = "0.0.291"
llama-cpp-python = {version = "0.1.83", extras = ["server"]}
pydantic = "2.0.3"
pyjwt = "2.6.0"
python = "^3.11"
uvicorn = "0.23.2"
cryptography = "41.0.3"
scikit-learn = "^1.3.0"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
